on:
  push:
    branches:
      - main

jobs:
  validate:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY
      shell: powershell
      if: ${{env.APIKEY != ''}}
      env:
        APIKEY: ${{ secrets.ApiKey }}