on: [pull_request]

jobs:
  validate_pwsh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: pwsh
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: pwsh